function Heart_GUI_preset(outputs)
close all
%% GUI
global outputs
global ConfigGUI
%% Get the display
pos = get(0, 'screensize'); %get the screensize
W=0.8*pos(3);
H=0.8*pos(4);
x0=50;
y0=50;
WIDTH=W-50-x0;
HEIGHT=H-100-y0;
%[left bottom width height],the most outer frame
ConfigGUI.Handle=figure('Units', 'Pixels', 'Position', [x0 y0 WIDTH HEIGHT],...
    'Resize','off','Name','Heart Model Set up','NumberTitle','Off',...
    'Tag','GUI');
% General model settings
ConfigGUI.model_settings = uipanel('Parent',ConfigGUI.Handle,...
    'Units','normalized',...
    'Position',[0.05 0.25 0.45 0.65],...
    'Title','General Model Settings',...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'HandleVisibility','callback',...
    'Tag','modelPanel');
% Pacemaker specific settings
ConfigGUI.pacemaker_settings = uipanel('Parent',ConfigGUI.Handle,...
    'Units','normalized',...
    'Position',[0.5 0.25 0.45 0.65],...
    'Title','Pacemaker Settings',...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'HandleVisibility','callback',...
    'Tag','pacemakerPanel');


% Parameter settings --- Drop Down
% parasMulti:
% Bradycardia+AV block+premature ventricular complex (PVC), RBBB (slow velocity):
% % SA BCL=1400; the automaticity of Node 24 (RBB) enabled (para48=0); path 10 backward enabled (para7=1.0); Path 15 cv=0.04, path 27 cv=0.4; 
% parasMulti2: PVC introduces PMT
% Bradycardia+AV block+premature ventricular complex (PVC), RBBB (complete blockage, i.e.,cv=0):
% % SA BCL=1400; the automaticity of Node 24 (RBB) enabled (para48=0); path 10 backward enabled (para7=1.0); Path 15 cv=0.04, path 27 cv=0;
% parasMulti3: extra VP introduces AVNRT
% % SA BCL=814; CS BCL=1194 enabled (para48=0); path 10 backward enabled (para7=0.8); ppR5
% cfg=[814,1194,2,0,0.100000000000000,0.250000000000000,278,0.0146200000000000,0.00872000000000000,2300,2,1,0.100000000000000,0.250000000000000,1.100000000000000,0.0700000000000000,0.0700000000000000,0.0700000000000000,0.0700000000000000];
%%parasNormal Normal but slight AV delay compared to device AVI.


uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.8 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Parameter choice:',...
    'HandleVisibility','callback');
ConfigGUI.parameterchoice = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.3 0.8 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String',{'Normal', 'parasMulti', 'parasMulti2', 'parasMulti3', 'Bradycardia'},...
    'HandleVisibility','callback',...
    'Tag','paramchoice');

uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.7 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Unit choice:',...
    'HandleVisibility','callback');
ConfigGUI.unitchoice = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.3 0.7 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String',{'Milliseconds','Seconds'},...
    'HandleVisibility','callback',...
    'Callback',@unitchange,...
    'Tag','unitchoice');
%%%% Notes in the TO ADD section
% uicontrol('Parent',ConfigGUI.model_settings,...
%     'Style','text',...
%     'Units','normalized',...
%     'Position',[0.6 0.3 0.35 0.15],...
%     'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
%     'String','These plots are currently not set up to change anything in the network GUI',...
%     'HandleVisibility','callback');
% Anymore model settings?
% - tutorial for the different node types
% - directly selecting a model to implant into the CLS system
% - model creation from scratch

% Whether to edit the existing model structure (opens the Heart Editing GUI after this one closes)
ConfigGUI.editmodel = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',[0.05 0.0 0.35 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Edit Model Network',...
    'HandleVisibility','callback',...
    'Tag','editmodel');

% User decides if they want a tutorial
ConfigGUI.tutorial = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',[0.35 0.0 0.35 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Tutorial',...
    'HandleVisibility','callback',...
    'Tag','tutorial');
% 
% strings = {'Plot 1:','Plot 2:', 'Plot 3:', 'Plot 4:', 'Plot 5:', 'Plot 6:'};
% left_positions = [0.05 0.05 0.05 0.05 0.05 0.05];
% bot_positions = [0.6 0.5 0.4 0.3 0.2 0.1];
% w_positions = [0.1 0.1 0.1 0.1 0.1 0.1];
% h_positions = [0.15 0.15 0.15 0.15 0.15 0.15];
% for idx = 1:length(strings)
%     uicontrol('Parent',ConfigGUI.model_settings,...
%         'Style','text',...
%         'Units','normalized',...
%         'Position',[left_positions(idx) bot_positions(idx) w_positions(idx) h_positions(idx)],...
%         'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
%         'String',strings{idx},...
%         'HandleVisibility','callback');
% end
% ConfigGUI.plot0 = uicontrol('Parent',ConfigGUI.model_settings,...
%     'Style','popupmenu',...
%     'Units','normalized',...
%     'Position',[0.15 0.6 0.25 0.15],...
%     'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
%     'String',{'AEGM', 'None', 'VEGM', 'Aget/Vget', 'AP/VP', 'AS/VS', 'AR/VR'},...
%     'HandleVisibility','callback');
% ConfigGUI.plot1 = uicontrol('Parent',ConfigGUI.model_settings,...
%     'Style','popupmenu',...
%     'Units','normalized',...
%     'Position',[0.15 0.5 0.25 0.15],...
%     'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
%     'String',{'VEGM', 'None', 'AEGM', 'Aget/Vget', 'AP/VP', 'AS/VS', 'AR/VR'},...
%     'HandleVisibility','callback');
% ConfigGUI.plot2 = uicontrol('Parent',ConfigGUI.model_settings,...
%     'Style','popupmenu',...
%     'Units','normalized',...
%     'Position',[0.15 0.4 0.25 0.15],...
%     'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
%     'String',{'Aget/Vget', 'None','AEGM', 'VEGM',  'AP/VP', 'AS/VS', 'AR/VR'},...
%     'HandleVisibility','callback');
% ConfigGUI.plot3 = uicontrol('Parent',ConfigGUI.model_settings,...
%     'Style','popupmenu',...
%     'Units','normalized',...
%     'Position',[0.15 0.3 0.25 0.15],...
%     'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
%     'String',{'AP/VP', 'None', 'AEGM', 'VEGM', 'Aget/Vget',  'AS/VS', 'AR/VR'},...
%     'HandleVisibility','callback');
% ConfigGUI.plot4 = uicontrol('Parent',ConfigGUI.model_settings,...
%     'Style','popupmenu',...
%     'Units','normalized',...
%     'Position',[0.15 0.2 0.25 0.15],...
%     'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
%     'String',{'AS/VS','None', 'AEGM', 'VEGM', 'Aget/Vget', 'AP/VP',  'AR/VR'},...
%     'HandleVisibility','callback');
% ConfigGUI.plot5 = uicontrol('Parent',ConfigGUI.model_settings,...
%     'Style','popupmenu',...
%     'Units','normalized',...
%     'Position',[0.15 0.1 0.25 0.15],...
%     'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
%     'String',{ 'AR/VR', 'None', 'AEGM', 'VEGM', 'Aget/Vget', 'AP/VP', 'AS/VS'},...
%     'HandleVisibility','callback');



ConfigGUI.closebutton = uicontrol('Parent',ConfigGUI.Handle,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.25 0.05 0.5 0.15],...
    'String','Close this GUI with the current settings on display',...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'HandleVisibility','callback',...
    'Callback',@closeGUI,...
    'Tag','closeButton');

% Pacemaker Settings

% 1. Whether to have a pacemaker at all in the modelling
%  -- decides whether to use the rest of this GUI section

uicontrol('Parent',ConfigGUI.pacemaker_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.8 0.1 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Model Type:',...
    'HandleVisibility','callback');
ConfigGUI.pacemaker = uicontrol('Parent',ConfigGUI.pacemaker_settings,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.2 0.8 0.2 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String',{'Full CLSfixed', 'Pacemaker', 'No Pacemaker'},...
    'HandleVisibility','callback',...
    'Callback',@deviceChange,...
    'Tag','editmodel');


% 2. What type of pacemaker TO ADD
% https://www.ncbi.nlm.nih.gov/books/NBK556011/ ---??????
% DDT
% Dual chamber/single chamber
% Resp Modulation (future work)

% 3. Pacemaker settings
%% desired (from CLSfixed/cfgs/Scfgf)
xa=1;
xc=0.05;
xc1=0.1;
xd=1;
xe=0.1;
avd=100;
vad=100;
uni_a=1;
Sens_a=0.6;
Amp_ap=500;
uni_v=1;
Sens_v=2.8;
Amp_vp=500;

strings = {'LRI (ms):', 'AVI (ms):', 'URI (ms):', 'VRP (ms):', 'PVARP (ms):'};
left_positions = [0.05 0.05 0.05 0.05 0.05];
bot_positions = [0.7 0.6 0.5 0.4 0.3];
h_positions = [0.1 0.1 0.1 0.1 0.1];
w_positions = [0.1 0.1 0.1 0.1 0.1];
for idx = 1:length(strings)
    uicontrol('Parent',ConfigGUI.pacemaker_settings,...
        'Style','text',...
        'Units','normalized',...
        'Position',[left_positions(idx) bot_positions(idx) w_positions(idx) h_positions(idx)],...
        'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
        'String',strings{idx},...
        'HandleVisibility','callback');
end
left_positions = [0.2 0.2 0.2 0.2 0.2];
bot_positions = [0.7 0.6 0.5 0.4 0.3];
h_positions = [0.1 0.1 0.1 0.1 0.1];
w_positions = [0.1 0.1 0.1 0.1 0.1];
string =[1000 80 500 230 250];
tags = {'lri', 'avi', 'uri', 'vrp', 'pvarp'};
for idx = 1:length(strings)
    uicontrol('Parent',ConfigGUI.pacemaker_settings,...
        'Style','edit',...
        'Units','normalized',...
        'Position',[left_positions(idx) bot_positions(idx) w_positions(idx) h_positions(idx)],...
        'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
        'String',string(idx),...
        'HandleVisibility','callback',...
        'Tag',tags{idx});
end

waitfor(ConfigGUI.Handle);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function deviceChange(hObject,eventdata)
lri=findobj('tag','lri');
avi=findobj('tag','avi');
uri=findobj('tag','uri');
vrp=findobj('tag','vrp');
pvarp=findobj('tag','pvarp');

if ConfigGUI.pacemaker.Value < 3
    lri.Style = 'edit';
    avi.Style = 'edit';
    uri.Style = 'edit';
    vrp.Style = 'edit';
    pvarp.Style = 'edit';
else
    lri.Style = 'text';
    avi.Style = 'text';
    uri.Style = 'text';
    vrp.Style = 'text';
    pvarp.Style = 'text';
end
    
end

function unitchange(hObject,eventdata)
ConfigGUI.parameterchoice.Value = 1;
if ConfigGUI.unitchoice.Value == 1
    ConfigGUI.parameterchoice.String = {'Normal', 'parasMulti', 'parasMulti2', 'parasMulti3', 'Bradycardia'};
else
    ConfigGUI.parameterchoice.String = {'Normal', 'AV Block'};
end
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function closeGUI(hObject,eventdata)
% outputs.plot0 = ConfigGUI.plot0.String{ConfigGUI.plot0.Value};
% outputs.plot1 = ConfigGUI.plot1.String{ConfigGUI.plot1.Value};
% outputs.plot2 = ConfigGUI.plot2.String{ConfigGUI.plot2.Value};
% outputs.plot3 = ConfigGUI.plot3.String{ConfigGUI.plot3.Value};
% outputs.plot4 = ConfigGUI.plot4.String{ConfigGUI.plot4.Value};
% outputs.plot5 = ConfigGUI.plot5.String{ConfigGUI.plot5.Value};
outputs.param = ConfigGUI.parameterchoice.String{ConfigGUI.parameterchoice.Value};
outputs.units = ConfigGUI.unitchoice.Value;
outputs.editmodel = ConfigGUI.editmodel.Value;
outputs.pacemaker = ConfigGUI.pacemaker.Value;
outputs.tutorial = ConfigGUI.tutorial.Value;

strings = {'LRI', 'AVI', 'URI', 'VRP', 'PVARP'};
base = [1000 80 500 230 250];

for i = 1:length(strings)
    q = findobj('tag',lower(strings(i)));
    val = str2double(get(q,'String'));
    if ~isnan(val)
        assignin('base',strings{i},val)
    else
        assignin('base',strings{i},base(i))
    end
end
close all
end
end