% Step 2: Define the reference model modules from /Lib
refmodules(1) = struct('module', 'Node_N', ...
                       'type', 'node', 'mtype', 'N');
refmodules(2) = struct('module', 'Node_M', ...
                       'type', 'node', 'mtype', 'M');
refmodules(3) = struct('module', 'Node_NM', ...
                       'type', 'node', 'mtype', 'NM');
refmodules(4) = struct('module', 'Path_model', ...
                       'type', 'path', 'mtype', 'straightLine');
refmodules(5) = struct('module', 'Electrode', ...
                       'type', 'electrode', 'mtype', 'straightLine');
save('Data/refmodules_default.mat','refmodules')
